steps:
- name: python:3.7
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r'
  - 'requirements.txt'


- name: python:3.7
  entrypoint: python3
  id: RUN-UNIT-TESTS
  args:
  - '-m'
  - 'nose2'
  - '-s'
  - 'tests'
  - '-c'
  - 'tests/nose2.cfg'
  waitFor:
  - INSTALL


- name: python:3.7
  entrypoint: python3
  id: SETUP_COVERALLS
  args:
    - '-m'
    - 'coveralls'
  env:
    - 'COVERALLS_REPO_TOKEN=246ghLDF9EVfsesHhuMr1rxz8wseGyPHp'


- name: python:3.7
  entrypoint: python3
  id: RUN-COVERAGE-TESTS
  args:
  - '-m'
  - 'coverage'
  - 'run'
  - '--source=test_calculator'
  - '-m'
  - 'nose2'
  - 'tests'
  waitFor:
  - INSTALL


- name: python:3.7
  entrypoint: python3
  id: RUN-END-END-TESTS
  args:
  - '-m'
  - 'python'
  - 'E2ETesting.py'
  waitFor:
  - INSTALL